### ISSUE TITLE
POST MVP: Set up indexes on UserId that we query frequently

### ISSUE THREAD

**Issue by LeonardZ0731** [googleinterns/NeighborGood#63]
While it's good to track the performance of our site, we should really attempt to make our tests stable. Furthermore, this is testing the performance of a local version of a dependency, which isn't really under our control. We can trust the Datastore helper to be reasonably performant in our unit tests.

This also brings up a question for me - have you set up indexes on the columns (like userId) that you intend to query frequently? If you do that, you can expect Datastore to perform adequately in these lookups, regardless of the amount of data.

If you do want to add an end-to-end test with junit, we could tag it and create a different Maven target that includes tests with the tag you choose. Then it won't run this test every time, which will be nice while developing the site, since those kinds of tests can be flaky and/or time consuming. See https://www.baeldung.com/junit-filtering-tests, for example.

_Originally posted by @peap in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjgyMTQ1NDI3OnYy/pull_request_review_threads/discussion_

**Comment by poncem91** [comment]
Closing issue since Datastore sets up indexes automatically.
